### PR TITLE
Info about npm package

### PR DESCRIPTION
**Pull request by shapkarin**
For [that repo](https://github.com/aeternity/superhero-button-react) it's needed some exports for the release.
At this time superhero-button-react is not released but it also can [use GitHub branch](https://github.com/aeternity/superhero-button-react/blob/3938878211ec71a171838ac6bf3adebf8da63c24/package.json#L28). So I'm not hurry up anyone.
And also I added info that superhero-button is published to npm.

### CODE REVIEW

**Comment by shapkarin** [comment]
not sure, but I guess I also can add
```js
export { icon };
```

**Comment by davidyuk** [comment]
It is not needed to update exports of this package if using it as here: https://github.com/aeternity/superhero-button-react/pull/3

Please, squash overlapping commits that update readme.

**Comment by shapkarin** [comment]
@davidyuk thanks for good refactoring, please check https://github.com/aeternity/superhero-button-react/pull/3/files#r452623446

>Please, squash overlapping commits that update readme.
OK

**Comment by shapkarin** [comment]
@davidyuk thanks for the refact, really. I know that it's [It's already pretty compatible](https://github.com/aeternity/jitsi-meet/issues/21#issuecomment-648379623) I'm afraid of memory

**Comment by shapkarin** [comment]
@davidyuk this exports can be useful for the other project maybe? Also I think to leave all about button API to this repo? How about that idea? And next create a better things at react version repo, like tooltip with value like we have at superhero.

**Comment by shapkarin** [comment]
@davidyuk I think I will do next:
- revert the commits to the one with docs about npm
- rename this PR to the some like `add info about npm`
- create the other one with API exports
- maybe add some more api methods to that PR, not sure now

**Comment by davidyuk** [comment]
> this exports can be useful for the other project maybe?

I don't think so. Let's wait for some actual use case.

**Comment by shapkarin** [comment]
@davidyuk I think that it's a good ideat to create a repo with exports like `superhero-utils` and next refact `superhero-ui`, `superhero-button` and `superhero-button-react` if the last will be exist.

**Comment by shapkarin** [comment]
@davidyuk I will remove some commits later, after #19 review

**Review by davidyuk — APPROVED** [review]
Looks ok, I'm not sure about the wording

**Comment by shapkarin** [comment]
@davidyuk I will think about that

**Comment by shapkarin** [comment]
@davidyuk I hope that wording is better and more straight forward

**Review by davidyuk — APPROVED** [review]

**Pull request merged**
