### PR TITLE
export createButtonInstance so that it can be used by other systems

### PR DESCRIPTION
**Pull request by Chima1707**
The PR exports a function that takes options and creates the button instance as its needed.

### CODE REVIEW

**Comment by shapkarin** [comment]
@Chima1707 what the difference with https://github.com/aeternity/superhero-button/pull/16/commits/aa093fac3b9cbf3193e068f5c84a9b6b0a36ba49 ?

**Comment by Chima1707** [comment]
> @Chima1707 what the difference with [aa093fa](https://github.com/aeternity/superhero-button/commit/aa093fac3b9cbf3193e068f5c84a9b6b0a36ba49) ?

This just export the function that creates the buttons element alone.

We need a way to create the button element anytime it is needed. we can now call this function in our wrapper components `componentDidMount` and `componentUpdate`. and insert the button element in our wrapper component

**Comment by shapkarin** [comment]
@Chima1707 why we need that until we have [this implementation](https://github.com/aeternity/superhero-button-react/blob/master/index.js)
What do you think about my thoughts about [memory leak](https://github.com/aeternity/jitsi-meet/issues/21#issuecomment-647151539)

**Comment by Chima1707** [comment]
> @Chima1707 why we need that until we have [this implementation](https://github.com/aeternity/superhero-button-react/blob/master/index.js)
> What do you think about my thoughts about [memory leak](https://github.com/aeternity/jitsi-meet/issues/21#issuecomment-647151539)

exported createButtonInstance function can now replace the `createButton` you referenced.
We dont need to create the button with the default exported API

**Comment by shapkarin** [comment]
> > @Chima1707 what the difference with [aa093fa](https://github.com/aeternity/superhero-button/commit/aa093fac3b9cbf3193e068f5c84a9b6b0a36ba49) ?
> 
> This just export the function that creates the buttons element alone.
> 
> We need a way to create the button element anytime it is needed. we can now call this function in our wrapper components `componentDidMount` and `componentUpdate`. and insert the button element in our wrapper component

Sorry, but I still can't get the difference with https://github.com/aeternity/superhero-button/commit/aa093fac3b9cbf3193e068f5c84a9b6b0a36ba49 and the reason. My reason was afraid of memory leak, you can check the link to the [that conversation](https://github.com/aeternity/jitsi-meet/issues/21#issuecomment-647151539). And of course the second reason is reimplement that with react. But if there is no any leak and until we have [this implementation](https://github.com/aeternity/superhero-button-react/blob/master/index.js) I can't get why we need any export.

**Comment by Chima1707** [comment]
> that conversation

Please can you point to me where the memory leak might happen?

**Comment by shapkarin** [comment]
> > that conversation
> 
> Please can you point to me where the memory leak might happen?

I had some other conversations as well and also not public. That what I thought:
- we create a lot of instances on every [account change](https://github.com/aeternity/jitsi-meet/blob/45bd3916726664bc151bb94a924701e4b569eb0e/react/features/toolbox/components/web/Toolbox.js#L345-L348)
- the garbage collector can't handle that because references and instances still exist in memory

**Comment by Chima1707** [comment]
``

> > > that conversation
> > 
> > 
> > Please can you point to me where the memory leak might happen?
> 
> I had some other conversations as well and also not public. That what I thought:
> 
> * we create a lot of instances on every [account change](https://github.com/aeternity/jitsi-meet/blob/45bd3916726664bc151bb94a924701e4b569eb0e/react/features/toolbox/components/web/Toolbox.js#L345-L348)
> * the garbage collector can't handle that because references and instances still exist in memory

I believe we should try this interface first, it is elegant. Then we can do proper performance testing. if we start exporting every function we loose encapsulation.

**Comment by shapkarin** [comment]
>I believe we should try this interface first, it is elegant. Then we can do proper performance testing. if we start exporting every function we loose encapsulation.

Sure. But in future. And at this day we can focus on other things. 

> But if there is no any leak and until we have [this implementation](https://github.com/aeternity/superhero-button-react/blob/master/index.js) I can't get why we need any export.

Maybe yours other export can avoid one problem in compare to [my](https://github.com/aeternity/superhero-button/commit/aa093fac3b9cbf3193e068f5c84a9b6b0a36ba49) – button branding change.

But I still think that we don't need any new export until there is no leak. And current export is [pretty compatible](https://github.com/aeternity/jitsi-meet/issues/21#issuecomment-648379623) with any other systems. But we can merge yours PR later maybe.

Let's wait the answer what other people think. Maybe @davidyuk or someone else have some thoughts.

**Comment by shapkarin** [comment]
Also for a future a nice idea will be to move all about API methods to the
one separate repo, like superhero-api-utils or superher-utils. In this way
we change some in one place and at next easily in least of two other repos
- superhero-ui, superhero-button. We talked about that too.

**Comment by davidyuk** [comment]
@Chima1707 Try the React component @shapkarin already mentioned. It should work fine. Otherwise please raise a specific issue. The current interface is enough simple and flexible, I don't see reasons to change it.

**Review by davidyuk — CHANGES_REQUESTED** [review]
@Chima1707 Try the React component @shapkarin already mentioned. It should work fine. Otherwise please raise a specific issue. The current interface is enough simple and flexible, I don't see reasons to change it.

**Comment by shapkarin** [comment]
@Chima1707 can it be used in a React component without
dangerouslySetInnerHTML?

**Comment by davidyuk** [comment]
As I got, the original issue of using this library in React is resolved without this change, so I'm closing this PR.

**Pull request closed without merging**
